### ISSUE TITLE
lbas_camera.launch

### ISSUE THREAD

**Issue by Archie945** [RemnantCloude/DetectUAV_YOLOv5#1]
roslaunch yolov5 yolov5.launch后
RLException: while processing /home/archie/test1_ws/src/track/launch/lbas_camera.launch:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/archie/test1_ws/src/track/launch/lbas_camera.launch'
The traceback for the exception was written to the log file
找不到lbas_camera.launch文件

**Comment by RemnantCloude** [comment]
这个launch文件是用于产生image话题的，可以删除掉。修改yolov5_node.py中的话题即可
```
image_sub = rospy.Subscriber("/camera/image_color", Image,
                                     imageCallback)
```
